# Generated by Django 3.0.5 on 2020-05-14 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PharmaClients', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='druglist',
            name='Added_By',
        ),
        migrations.AddField(
            model_name='druglist',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
