# Generated by Django 3.0.5 on 2020-05-15 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PharmaClients', '0002_auto_20200514_0536'),
    ]

    operations = [
        migrations.AddField(
            model_name='druglist',
            name='DateAdded',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
