# Generated by Django 3.0.5 on 2020-05-18 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PharmaClients', '0003_druglist_dateadded'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FoodName', models.CharField(max_length=250)),
                ('FoodPrice', models.IntegerField(default=5)),
                ('FoodPreview', models.ImageField(upload_to='')),
                ('DateAdded', models.DateField(auto_now=True)),
            ],
        ),
        migrations.DeleteModel(
            name='DrugList',
        ),
    ]
