# Generated by Django 3.0.5 on 2020-06-26 11:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('PharmaClients', '0005_auto_20200518_0702'),
    ]

    operations = [
        migrations.CreateModel(
            name='DrugOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Order_Date', models.DateTimeField(auto_now=True)),
                ('Quantity', models.IntegerField(default=1)),
                ('Drug_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Order', to='PharmaClients.DrugList')),
                ('Ordered_By', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Order', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
