# Generated by Django 3.0.5 on 2020-06-27 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PharmaClients', '0006_drugorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='drugorder',
            name='TotalPrice',
            field=models.IntegerField(default=1),
        ),
    ]
