# Generated by Django 3.0.5 on 2020-05-14 14:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Bio', models.TextField(blank=True)),
                ('Profile_Image', models.ImageField(upload_to='', verbose_name='<django.db.models.query_utils.DeferredAttribute object at 0x000002279A436A48>/')),
                ('Birth_Date', models.DateField()),
                ('Address', models.CharField(default=None, max_length=255)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
