# Generated by Django 3.0.5 on 2020-05-14 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='Profile_Image',
            field=models.ImageField(storage='<django.db.models.query_utils.DeferredAttribute object at 0x00000286BE6F6988>/', upload_to=''),
        ),
    ]
