# Generated by Django 3.0.5 on 2020-05-14 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0003_auto_20200514_0937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='Profile_Image',
            field=models.ImageField(storage='<function AbstractBaseUser.get_username at 0x00000211305BF0D8>', upload_to=''),
        ),
    ]
